import { describe,it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { MemoryStorage } from '../src/storage/memory.js';
import { DictationService,styleScope } from '../src/domain/dictation-service.js';
import { FeedbackService } from '../src/domain/feedback-service.js';
import { FakeLlm,FakeStt,safeGuard } from './helpers.js';
import type { CorrectionType } from '../src/types.js';
function setup(type:CorrectionType='TERM_CORRECTION'){
  const storage=new MemoryStorage();const llm=new FakeLlm(input=>{const d=JSON.parse(input.user);if(input.schemaName.startsWith('sayit_rewrite'))return {final_text:d.raw,applied_terms:[],transformations:[]};if(input.schemaName.includes('guard'))return safeGuard();return {items:d.spans.map((_:unknown,i:number)=>({span_index:i,type,confidence:0.99,reason:'fixture'})),style:{verbosity:null,formality:null,bulletPreference:null}};});
  const create=(raw:string)=>storage.transaction('u',tx=>new DictationService(new FakeStt(),llm,tx,{semanticGuardEnabled:true}).create({userId:'u',rawTranscript:raw,context:{type:'ai_prompt'}}));
  const submit=async(raw:string,final:string,extra:Record<string,unknown>={})=>{const d=await create(raw);const body={event_id:randomUUID(),output_sha256:d.outputHash,final_text:final,attribution:'dictation_span' as const,...extra};const result=await storage.transaction('u',tx=>new FeedbackService(llm,tx).submit('u',d.id,body));return {d,body,result};};
  return {storage,llm,create,submit};
}
describe('feedback learning safety',()=>{
  it('learns case/spacing preferred spelling immediately',async()=>{const s=setup();const r=await s.submit('用 thread chat。','用 ThreadChat。');expect(r.result.learnedVocabulary).toEqual(['ThreadChat']);expect((await s.storage.listVocabulary('u'))[0]!.aliases).toContain('thread chat');});
  it('keeps phonetic correction as a candidate until independent repeated evidence',async()=>{const s=setup();await s.submit('用一二逼。','用E2B。');let v=(await s.storage.listVocabulary('u'))[0]!;expect(v.status).toBe('candidate');expect(v.aliases).toEqual([]);await s.submit('启动一二逼。','启动E2B。');v=(await s.storage.listVocabulary('u'))[0]!;expect(v.status).toBe('active');expect(v.aliases).toEqual(['一二逼']);});
  it('explicit term confirmation can activate a narrow mapping',async()=>{const s=setup('UNKNOWN');const r=await s.submit('用一二逼。','用E2B。',{confirmed_terms:[{before:'一二逼',after:'E2B'}]});expect(r.result.learnedVocabulary).toEqual(['E2B']);});
  it.each([['限制 6 次。','限制 16 次。'],['不要删除。','删除。'],['先实现服务。','先实现服务，明天发布。']])('does not teach dangerous edits even if model calls them lexical',(async(a,b)=>{const s=setup();await s.submit(a,b);expect(await s.storage.listVocabulary('u')).toHaveLength(0);}));
  it('whole-message edits never teach vocabulary',async()=>{const s=setup();const r=await s.submit('用一二逼。','前缀，用E2B。',{attribution:'whole_message'});expect(r.result.reason).toBe('unreliable_span_attribution');expect(r.result.postEditCost).toBeNull();expect(await s.storage.listVocabulary('u')).toHaveLength(0);});
  it('unchanged output does not increment style or dictionary',async()=>{const s=setup();const r=await s.submit('hi','hi');expect(r.result.status).toBe('no_change');expect(await s.storage.getStyleProfile('u',styleScope({type:'ai_prompt'}))).toBeNull();});
  it('repeated simultaneous feedback is exactly once',async()=>{const s=setup();const {d,body}=await s.submit('用一二逼。','用E2B。');const calls=s.llm.calls.length;await Promise.all(Array.from({length:8},()=>s.storage.transaction('u',tx=>new FeedbackService(s.llm,tx).submit('u',d.id,body))));expect(s.llm.calls).toHaveLength(calls);expect((await s.storage.listVocabulary('u'))[0]!.frequency).toBe(1);});
  it('conflicting final edits cannot rewrite already learned feedback',async()=>{const s=setup();const {d,body}=await s.submit('用一二逼。','用E2B。');await expect(s.storage.transaction('u',tx=>new FeedbackService(s.llm,tx).submit('u',d.id,{...body,final_text:'用别的。'}))).rejects.toThrow('feedback_already_finalized');});
  it('deleted terms are not silently relearned',async()=>{const s=setup();await s.submit('用 thread chat。','用 ThreadChat。');const v=(await s.storage.listVocabulary('u'))[0]!;await s.storage.deleteVocabulary('u',v.id);await s.submit('打开 thread chat。','打开 ThreadChat。');expect((await s.storage.listVocabulary('u'))[0]!.status).toBe('blocked');expect((await s.storage.listRecentCorrections('u')).some(c=>c.learn)).toBe(false);});
  it('rejects fabricated or duplicated span indices atomically',async()=>{const s=setup();const d=await s.create('用 foo。');s.llm.handler=()=>({items:[{span_index:99,type:'SPELLING',confidence:1,reason:'bad'}],style:{verbosity:null,formality:null,bulletPreference:null}});await expect(s.storage.transaction('u',tx=>new FeedbackService(s.llm,tx).submit('u',d.id,{event_id:randomUUID(),output_sha256:d.outputHash,final_text:'用 Foo。',attribution:'dictation_span'}))).rejects.toThrow('invalid_feedback_alignment');expect((await s.storage.getDictation('u',d.id))!.feedback).toBeUndefined();expect(await s.storage.listVocabulary('u')).toHaveLength(0);});
  it('does not train when personalization is disabled',async()=>{const s=setup();await s.storage.setPersonalization('u',false);const r=await s.submit('thread chat','ThreadChat');expect(r.result.reason).toBe('personalization_disabled');});
  it('rolls back all mutations on transactional failure',async()=>{const s=setup();await expect(s.storage.transaction('u',async tx=>{await tx.upsertVocabulary({userId:'u',canonical:'Oops',source:'manual'});throw Error('rollback');})).rejects.toThrow('rollback');expect(await s.storage.listVocabulary('u')).toHaveLength(0);});
});
